#!bin/bash
docker build --tag="$project_name" Docker/ 
docker save --output="$project_name.tar" $project_name

cp $project_name.tar installer/$project_name.tar
cp setup.sh installer/setup.sh
tar -cvf $installer_name installer/* 
gzip $installer_name
