#!bin/bash
# This file builds a docker image, then tars and zips
# it into a file with a setup file (setup.sh)

# Copyright 2014 freedops.org
#
# This file is part of the freedops.org tools collection.
#
# The freedops.org tools collection is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# The freedops.org tools collection is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the freedops.org tools collection.
#
# If not, see <http://www.gnu.org/licenses/>.

docker build --tag="$project_name" Docker/ 
docker save --output="$project_name.tar" $project_name

cp $project_name.tar installer/$project_name.tar
cp setup.sh installer/setup.sh
tar -cvf $installer_name installer/* 
gzip $installer_name
