# Freedops Dev env installer 
#
# VERSION       1.0
#
# 
# This file is used to generate the base installer
###########################################################

# Copyright 2014 freedops.org
#
# This file is part of the freedops.org tools collection.
#
# The freedops.org tools collection is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# The freedops.org tools collection is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the freedops.org tools collection.
#
# If not, see <http://www.gnu.org/licenses/>.

FROM $root_dist:$dist_tag

MAINTAINER $owner, $owner_email


# housekeeping

# make sure the package repository is up to date

#$os_extras
RUN $update_os
RUN $install_os_sw $extra_sw

#$additional_commands1
#RUN systemctl start docker
#$additional_commands2

ADD Container/runfile.sh /var/local/runfile/runfile.sh
VOLUME /var/lib/docker
CMD wrapdocker
 

