# Freedops Dev env installer 
#
# VERSION       1.0

# 
# this file is used to generate the base installer
FROM $root_dist:$dist_tag

MAINTAINER $owner, $owner_email


# housekeeping

# make sure the package repository is up to date

$os_extras
RUN $update_os
RUN $install_os_sw $extra_sw

ADD Container/runfile.sh /var/local/runfile/runfile.sh
 

