#!/bin/bash
# This file creates a script that updates a project,
# builds it, then tests it.

# Copyright 2014 freedops.org
#
# This file is part of the freedops.org tools collection.
#
# The freedops.org tools collection is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# The freedops.org tools collection is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the freedops.org tools collection.
#
# If not, see <http://www.gnu.org/licenses/>.


# run while in the project directory
#$update_project
$build_command
$test_command 

