#!/bin/bash
# This file creates a script that takes a docker image
# sets up a shared volume and load a pre-specified project_destination
# into it.

# Copyright 2014 freedops.org
#
# This file is part of the freedops.org tools collection.
#
# The freedops.org tools collection is free software: you can redistribute it
# and/or modify it under the terms of the GNU General Public License as
# published by the Free Software Foundation, either version 3 of the License,
# or (at your option) any later version.
#
# The freedops.org tools collection is distributed in the hope that it will
# be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with the freedops.org tools collection.
#
# If not, see <http://www.gnu.org/licenses/>.

if [ ! $1 ];then
    echo Error, no host shared volume directory specified, format: setup.sh shared_dir
    exit
fi

# Set up the docker file, create a shared volume with the host
docker load --input="$project_name.tar"
docker run -v $1:$project_destination:rw --workdir="$project_destination" $project_name $get_project $project_destination/$project_name
docker commit $(docker ps -lq) $project_name
docker run -v $1:$project_destination:rw --workdir="$project_destination" $project_name chmod -R 777 $project_destination/$project_name
docker commit $(docker ps -lq) $project_name
docker run --privileged -v $1:$project_destination:rw --workdir="$project_destination/$project_name" $project_name sh /var/local/runfile/runfile
docker commit $(docker ps -lq) $project_name
docker run --privileged -v $1:$project_destination:rw --workdir="$project_destination" $project_name chmod -R 777 $project_destination
docker commit $(docker ps -lq) $project_name
# Create a build and test script
echo docker run --privileged -v $1:$project_destination:rw --workdir="$project_destination/$project_name" $project_name sh /var/local/runfile/runfile > $1/build_test
chmod 755 build_test

