#!bin/bash
if [ ! $1 ];then
    echo Error, no host shared volume directory specified, format: setup.sh shared_dir
    exit
fi

# Set up the docker file, create a shared volume with the host
docker load -input="$installer_name.tar"
docker run -v $local_folder:$project_destination:rw --workdir="$project_destination" $project_name $get_project $project_destination/$project_name
docker commit $(docker ps -lq) $project_name
docker run -v $local_folder:$project_destination:rw --workdir="$project_destination" $project_name chmod -R 777 $project_destination/$project_name
docker commit $(docker ps -lq) $project_name
docker run -v $local_folder:$project_destination:rw $project_name ls $project_destination
docker commit $(docker ps -lq) $project_name
docker run -v $local_folder:$project_destination:rw --workdir="$project_destination/$project_name" $project_name ls
docker run -v $local_folder:$project_destination:rw --workdir="$project_destination/$project_name" $project_name sh /var/local/runfile/runfile.sh
